# docker-compose.prod.yml
version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: sporty_postgres_prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sporty}
      POSTGRES_USER: ${POSTGRES_USER:-sporty_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-sporty_user} -d ${POSTGRES_DB:-sporty}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sporty_network

  # FastAPI Backend
  backend:
    build: .
    container_name: sporty_backend_prod
    environment:
      # Database Configuration
      USE_DATABASE: "true"
      DATABASE_URL: "postgresql://${POSTGRES_USER:-sporty_user}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-sporty}"
      
      # AI Provider Configuration
      AI_PROVIDER: "${AI_PROVIDER:-openai}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      OPENAI_MODEL: "${OPENAI_MODEL:-gpt-3.5-turbo}"
      
      # Ollama Configuration (if using Ollama)
      OLLAMA_BASE_URL: "${OLLAMA_BASE_URL:-http://ollama:11434}"
      OLLAMA_MODEL: "${OLLAMA_MODEL:-llama2}"
      
      # Strava Configuration
      STRAVA_CLIENT_ID: "${STRAVA_CLIENT_ID}"
      STRAVA_CLIENT_SECRET: "${STRAVA_CLIENT_SECRET}"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - sporty_network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: sporty_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # For SSL certificates
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - sporty_network

volumes:
  postgres_data:

networks:
  sporty_network:
    driver: bridge
